apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: dash007/vprofiledb:latest
          securityContext:
            runAsUser: 999
          volumeMounts:
            - mountPath: /mount/data
              name: vpro-db-data2
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vpro-db-data2
          # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: vol-0b0a7cae742bf30f1
            fsType: ext4
